FROM node:23.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN npm ci
RUN npm install react-scripts@5.0.1 -g
COPY frontend/. ./
RUN npm run build

FROM nginx:1.27.2-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY frontend/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
