version: '3.9'

name: shopping-online-prod

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - back
  backend-prod:
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - FRONTEND_CORS_URL=${CORS_URL}
    depends_on:
      - db
    networks:
      - front
      - back
  frontend-prod:
    build:
      dockerfile: ./frontend/Dockerfile-prod
    ports:
      - "80:80"
    depends_on:
      - backend-prod
    networks:
      - front
networks:
  front:
  back:
volumes:
  db-data: