version: '3.9'

name: shopping-online-dev

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shopping-online-dev
      - POSTGRES_USER=alexprokopiev
      - POSTGRES_PASSWORD=admin
    networks:
      - back
  backend:
    build:
      dockerfile: ./backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shopping-online-dev
    depends_on:
      - db
    networks:
      - front
      - back
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - front
networks:
  front:
  back:
volumes:
  db-data: