spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/react_spring_app
    username: alexprokopiev
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
settings:
  cors-origin: ${FRONTEND_CORS_URL:http://localhost:3000}